# Sonar project analysis properties overrides
# Automatic analysis ignores this file, and uses .sonarcloud.properties instead

sonar.projectKey=LizardByte_tray

sonar.exclusions=third-party/**

sonar.cfamily.reportingCppStandardOverride=c++17
